---IndustryModifiers
NDefines.NBuildings.MAX_SHARED_SLOTS = 49
NDefines.NBuildings.MAX_BUILDING_LEVELS = 49
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 10
NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 300
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 2
---BegoneClouds
NDefines_Graphics.NGraphics.DRAW_FOW_CUTOFF = 0;
NDefines_Graphics.NGraphics.DRAW_FOW_FADE_LENGTH = 0; 
--SpamMoreDivs
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 10000000
--LandCombatChanges
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.000
NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 0.6
NDefines.NMilitary.TRAINING_ATTRITION = 0.03
NDefines.NMilitary.STRATEGIC_SPEED_BASE = 10.0
---HigherExperienceCap
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 2000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 2000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 2000
---SpeedGoZoomMaybe
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 1000
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 100
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36
NDefines.NCountry.EVENT_PROCESS_OFFSET = 25
NDefines.NGame.GAME_SPEED_SECONDS = { 0.35, 0.15, 0.1, 0.035, 0.0 }
NDefines.NCountry.COUNTRY_SCORE_MULTIPLIER = 0
NDefines.NCountry.ARMY_SCORE_MULTIPLIER = 0
NDefines.NCountry.NAVY_SCORE_MULTIPLIER = 0
NDefines.NCountry.AIR_SCORE_MULTIPLIER = 0
NDefines.NCountry.INDUSTRY_SCORE_MULTIPLIER = 0 
NDefines.NCountry.PROVINCE_SCORE_MULTIPLIER = 0